version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.2
    parallelism: 30
    steps:
      - checkout
      - run: echo $BRAINTREE_ENV
      - run:
          name: print env
          command: |
              ruby \<<EOD
                puts ENV['BRAINTREE_ENV']
                puts ENV['BRAINTREE_ENV'].to_sym
              EOD
      - run: BRAINTREE_ENVIRONMENT=$BRAINTREE_ENV ruby -e "puts %[hello from process #{ENV['BRAINTREE_ENVIRONMENT'].to_sym}]"
              
              
